### ISSUE TITLE
Show progress of the tests in progress during `make test`

### ISSUE THREAD

**Issue by samos123** [substratusai/substratusai.github.io#30]
The progress should be written to stdout of things like terraform apply. That way you know where you are.

Running `ps` I can see that `terraform apply` is running but no idea how to get the output of the terraform apply run.

This will also be important for when we incorprate this test into the CI otherwise it will be hard to troubleshoot CI jobs without having any logs.

@brandonjbjelland I remember when you were screensharing you had a way to show the progress already.

**Comment by brandonjbjelland** [comment]
You'll need to make a couple edits here (I haven't tested what happens when a non-existent directory is used), but invoking that script as you run tests will show you the notebook ouptuts in realtime.

**Comment by brandonjbjelland** [comment]
This is now supported in [CI](https://github.com/substratusai/substratusai.github.io/actions/runs/5723797837/job/15509034597) and also [locally](https://github.com/substratusai/substratusai.github.io/blob/main/README.md#testing). Local, I need to run the utility in a separate terminal. Not the worst but also not the best.
